## 1. Importation des Bibliothèques et des Données

In [276]:
import pandas as pd 
import numpy as np

In [277]:
Cat_Prds = pd.read_excel('Données Catégories de Produits.xlsx')
Frs = pd.read_excel('Données Fournisseurs.xlsx')
Mag = pd.read_excel('Données Magasins.xlsx')
Prds = pd.read_excel('Données Produits.xlsx')

T1 = pd.read_csv('Données_Transaction_2025_1.csv', sep=';', encoding='utf-8-sig')
T2 = pd.read_csv('Données_Transaction_2025_2.csv', sep=';', encoding='utf-8-sig')
T3 = pd.read_csv('Données_Transaction_2025_3.csv', sep=';', encoding='utf-8-sig')
T4 = pd.read_csv('Données_Transaction_2025_4.csv', sep=';', encoding='utf-8-sig')

## 2. Nettoyage et Préparation des Données

##  2.1 Catégories de Produits

In [278]:
Cat_Prds.head()

,Category_id,Product_Category,Category_Image
0,PROD-001,Alimentaion animale,https://images.pexels.com/photos/8434637/pexel...
1,PROD-002,Produits Bébé,https://media.istockphoto.com/id/1124651257/ph...
2,PROD-003,Charcuterie,https://media.istockphoto.com/id/945849940/pho...
3,PROD-004,Boulangerie,https://media.istockphoto.com/id/496564915/pho...
4,PROD-005,Vêtements,https://images.pexels.com/photos/3768005/pexel...

In [279]:
Cat_Prds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Category_id       16 non-null     object
 1   Product_Category  16 non-null     object
 2   Category_Image    16 non-null     object
dtypes: object(3)
memory usage: 516.0+ bytes

In [280]:
Cat_Prds.isnull().sum()

Category_id         0
Product_Category    0
Category_Image      0
dtype: int64

In [281]:
Cat_Prds.duplicated().sum()

np.int64(0)

In [282]:
Cat_Prds['Category_id'].is_unique

True

## 2.2 Fournisseurs

In [283]:
Frs.head()

,Fournisseur_id,Fournisseur_Nom,Founisseur_image
0,SUPP-001,Produits Importés,https://www.gtreview.com/wp-content/uploads/20...
1,SUPP-002,Produits Locals,https://www.mapbusiness.ma/wp-content/uploads/...
2,SUPP-003,COPAG,https://www.copag.ma/themes/custom/copag/asset...
3,SUPP-004,Whiskas,https://miro.medium.com/0*SNO81Zy5vwyNAUVn
4,SUPP-005,Activpet,https://karmopedia.pl/wp-content/uploads/2016/...

In [284]:
Frs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251 entries, 0 to 250
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Fournisseur_id    251 non-null    object
 1   Fournisseur_Nom   251 non-null    object
 2   Founisseur_image  251 non-null    object
dtypes: object(3)
memory usage: 6.0+ KB

In [285]:
Frs.isnull().sum()

Fournisseur_id      0
Fournisseur_Nom     0
Founisseur_image    0
dtype: int64

In [286]:
Frs.duplicated().sum()

np.int64(0)

In [287]:
Frs['Fournisseur_id'].is_unique

True

## 2.3 Magasins

In [288]:
Mag.head()

,id_magasin,Zone,Ville,Région,Adresse
0,SM-001,AIN CHOCK/QUARTIER CALIFORNIE,Casablanca,Casablanca-Settat,Californie 1
1,SM-002,Casa/Aïn Chock/Al Fateh,Casablanca,Casablanca-Settat,Ain Chock 1
2,SM-003,Casa/Aïn Chock/Bd Amgala,Casablanca,Casablanca-Settat,Yassmine 2
3,SM-004,Casa/Aïn Chock/Bd Dakhla,Casablanca,Casablanca-Settat,Ahmra 2
4,SM-005,Casa/Aïn Chock/Bd Fès,Casablanca,Casablanca-Settat,Californie 2

In [289]:
Mag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_magasin  309 non-null    object
 1   Zone        309 non-null    object
 2   Ville       309 non-null    object
 3   Région      309 non-null    object
 4   Adresse     309 non-null    object
dtypes: object(5)
memory usage: 12.2+ KB

In [290]:
Mag.duplicated().sum()

np.int64(0)

In [291]:
Mag = Mag.rename(columns={
    "id_magasin" : "magasin_id",
    "Région" : "Region"
})

In [292]:
Mag.head()

,magasin_id,Zone,Ville,Region,Adresse
0,SM-001,AIN CHOCK/QUARTIER CALIFORNIE,Casablanca,Casablanca-Settat,Californie 1
1,SM-002,Casa/Aïn Chock/Al Fateh,Casablanca,Casablanca-Settat,Ain Chock 1
2,SM-003,Casa/Aïn Chock/Bd Amgala,Casablanca,Casablanca-Settat,Yassmine 2
3,SM-004,Casa/Aïn Chock/Bd Dakhla,Casablanca,Casablanca-Settat,Ahmra 2
4,SM-005,Casa/Aïn Chock/Bd Fès,Casablanca,Casablanca-Settat,Californie 2

In [293]:
Mag['magasin_id'].is_unique

True

In [294]:
Mag['magasin_id'].duplicated().sum()

np.int64(0)

In [295]:
Mag.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   magasin_id  309 non-null    object
 1   Zone        309 non-null    object
 2   Ville       309 non-null    object
 3   Region      309 non-null    object
 4   Adresse     309 non-null    object
dtypes: object(5)
memory usage: 12.2+ KB

In [223]:
Mag = Mag.drop(columns=['Région'], errors = 'ignore')

In [224]:
Mag.head(1)

,magasin_id,Zone,Ville,Region,Adresse
0,SM-001,AIN CHOCK/QUARTIER CALIFORNIE,Casablanca,Casablanca-Settat,Californie 1

## 2.4 Produits

In [296]:
Prds.head()

,Produit_SKU,Produit_Désignation,Prix d'achat,Prix de vente,Fournisseur,Catégorie de Produit
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale

In [297]:
Prds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13267 entries, 0 to 13266
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Produit_SKU           13267 non-null  object
 1   Produit_Désignation   13267 non-null  object
 2   Prix d'achat          13267 non-null  float64
 3   Prix de vente         13267 non-null  float64
 4   Fournisseur           13267 non-null  object
 5   Catégorie de Produit  13267 non-null  object
dtypes: float64(2), object(4)
memory usage: 622.0+ KB

In [298]:
Prds.duplicated().sum()

np.int64(0)

In [299]:
Prds['Catégorie de Produit'].unique()

array(['Alimentation animale', 'Produits Bébé', 'Charcuterie',
       'Boulangerie', 'Vêtements', 'Confiseries', 'Boissons',
       'Electroménager', 'Courses', 'Loisirs', 'Hygiène',
       'Produits surgelés', 'Entretien & Nettoyage', 'Produits laitiers',
       'Épices', 'Électroniques'], dtype=object)

In [300]:
Prds['Fournisseur'].nunique()

251

In [301]:
Prds['Fournisseur'].value_counts().head()

Fournisseur
COPAG           623
Taous           397
Aiguebelle      364
LES DOMAINES    317
VCR SODALMU     284
Name: count, dtype: int64

In [302]:
Prds['Fournisseur'].value_counts().tail()

Fournisseur
Ajax                 2
Clorets              1
Tic Tac              1
Derma                1
Produits Importés    1
Name: count, dtype: int64

In [303]:
Prds = Prds.rename(columns={
    "Produit_Désignation" : "Produit_Designation",
    "Prix d'achat" : "Prix_Achat",
    "Prix de vente" : "Prix_vente",
    "Fournisseur" : "Fournisseur_Nom",
    "Catégorie de Produit" : "Product_Category"
})

In [304]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale

In [305]:
Prds['Fournisseur_Nom'] = Prds.get('Fournisseur_Nom', pd.Series(dtype=str)).replace({'LAND OR': 'LANDOR'})

In [306]:
Prds = Prds.merge(
    Frs[['Fournisseur_id','Fournisseur_Nom']],
    on = 'Fournisseur_Nom',
    how = 'left'
)

In [307]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category,Fournisseur_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale,SUPP-003
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale,SUPP-003
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale,SUPP-003
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale,SUPP-003
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale,SUPP-003

In [308]:
Prds[Prds['Fournisseur_id'].isna()]

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category,Fournisseur_id
620,10040-21,Pastrami de Boeuf Sous Vide - Charcuterie - Ja...,26.1250,27.50,Copag,Charcuterie,NaN
622,10040-23,Salami de Bœuf Jayda 80g,12.8725,13.55,Copag,Charcuterie,NaN
662,10040-63,Luncheon de Bœuf - Charcuterie - Jayda 300g,12.8250,13.50,Copag,Charcuterie,NaN
663,10040-64,Luncheon de Bœuf - Charcuterie - Jayda 300g.,15.6750,16.50,Copag,Charcuterie,NaN
691,10040-92,Chorizo de bœuf Jayda 80g.,14.0600,14.80,Copag,Charcuterie,NaN
...,...,...,...,...,...,...,...
13035,10160-2870,Sucre Blanc en Petits Cubes Sukari 500g.,6.3000,9.00,Cosumar,Épices,NaN
13036,10160-2871,Sucre Cristallisé Sukari 5kg,28.9100,41.30,Cosumar,Épices,NaN
13039,10160-2874,Sucre Roux Forme Cube Sucre D'Or Sukari 500g.,11.1650,15.95,Cosumar,Épices,NaN
13040,10160-2875,Sucre Roux Granulé Sucre D'Or Sukari 1kg,15.5750,22.25,Cosumar,Épices,NaN
13209,10160-3044,Thym GAYA 80g.,14.4550,20.65,Gaya,Épices,NaN

In [309]:
Prds.isnull().sum()

Produit_SKU              0
Produit_Designation      0
Prix_Achat               0
Prix_vente               0
Fournisseur_Nom          0
Product_Category         0
Fournisseur_id         161
dtype: int64

In [310]:
Prds[Prds['Fournisseur_id'].isna()][
    ['Produit_SKU', 'Fournisseur_Nom']
].drop_duplicates()

      Produit_SKU Fournisseur_Nom
620      10040-21           Copag
622      10040-23           Copag
662      10040-63           Copag
663      10040-64           Copag
691      10040-92           Copag
...           ...             ...
13035  10160-2870         Cosumar
13036  10160-2871         Cosumar
13039  10160-2874         Cosumar
13040  10160-2875         Cosumar
13209  10160-3044            Gaya

[161 rows x 2 columns]

In [311]:
Prds[Prds['Fournisseur_id'].isna()]['Fournisseur_Nom'].value_counts()

Fournisseur_Nom
Lu         69
Gaya       53
Copag      18
Cosumar    13
Isabel      5
Land Or     2
Clorets     1
Name: count, dtype: int64

In [312]:
Frs['Fournisseur_Nom'] = (
    Frs['Fournisseur_Nom']
    .astype(str)
    .str.strip()
    .str.upper()
)

Prds['Fournisseur_Nom'] = (
    Prds['Fournisseur_Nom']
    .astype(str)
    .str.strip()
    .str.upper()
)

In [313]:
Prds = Prds.merge(
    Frs[['Fournisseur_id' , 'Fournisseur_Nom']],
    on = 'Fournisseur_Nom',
    how = 'left'
)

In [314]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category,Fournisseur_id_x,Fournisseur_id_y
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale,SUPP-003,SUPP-003
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale,SUPP-003,SUPP-003
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale,SUPP-003,SUPP-003
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale,SUPP-003,SUPP-003
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale,SUPP-003,SUPP-003

In [315]:
Prds['Fournisseur_id_x'].isna().sum()

np.int64(161)

In [316]:
Prds['Fournisseur_id_y'].isna().sum()

np.int64(8)

In [317]:
Prds = Prds.drop(columns=['Fournisseur_id_x'])

In [318]:
Prds = Prds.rename(columns={'Fournisseur_id_y' : 'Fournisseur_id'})

In [319]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category,Fournisseur_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale,SUPP-003
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale,SUPP-003
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale,SUPP-003
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale,SUPP-003
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale,SUPP-003

In [320]:
Prds.isna().sum()

Produit_SKU            0
Produit_Designation    0
Prix_Achat             0
Prix_vente             0
Fournisseur_Nom        0
Product_Category       0
Fournisseur_id         8
dtype: int64

In [321]:
Prds[Prds['Fournisseur_id'].isna()]['Fournisseur_Nom'].value_counts()

Fournisseur_Nom
ISABEL     5
LAND OR    2
CLORETS    1
Name: count, dtype: int64

In [322]:
Prds[Prds['Fournisseur_id'].isna()][
    ['Produit_SKU', 'Produit_Designation', 'Fournisseur_Nom']
]

,Produit_SKU,Produit_Designation,Fournisseur_Nom
1931,10070-765,Chewing-Gum Citron et Menthe Clorets 10 unités,CLORETS
9819,10150-732,Fromage Fondu Land Or 64 portions,LAND OR
9820,10150-733,Fromage Fondu Land' Or 48 portions.,LAND OR
10706,10160-229,Conserve de Thon à l'Huile de Tournesol Isabel...,ISABEL
11524,10160-1047,Conserve de Thon à la Sauce Tomate Isabel 80g,ISABEL
12620,10160-2143,Pack de Trois Conserves de Thon à l'Huile de T...,ISABEL
12624,10160-2147,Pack de Trois Conserves de Thon à la Sauce lah...,ISABEL
12626,10160-2149,Pack de Trois Conserves de Thon à la Sauce Tom...,ISABEL

In [323]:
Frs[Frs['Fournisseur_Nom'].str.contains(
    'CLORETS|LAND|ISABEL',
    case=False,
    na=False
)]

,Fournisseur_id,Fournisseur_Nom,Founisseur_image
191,SUPP-213,LANDOR,https://encrypted-tbn0.gstatic.com/images?q=tb...

In [324]:
Prds = Prds.dropna(subset=['Fournisseur_id'])

In [325]:
Prds['Fournisseur_id'].isna().sum()

np.int64(0)

In [326]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Fournisseur_Nom,Product_Category,Fournisseur_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,COPAG,Alimentation animale,SUPP-003
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,COPAG,Alimentation animale,SUPP-003
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,COPAG,Alimentation animale,SUPP-003
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,COPAG,Alimentation animale,SUPP-003
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,COPAG,Alimentation animale,SUPP-003

In [327]:
Prds['Fournisseur_Nom'] = Prds.get('Fournisseur_Nom', pd.Series(dtype=str)).replace({'LAND OR': 'LANDOR'})

In [328]:
Prds = Prds.drop(columns=['Fournisseur_Nom'])

In [329]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003

In [330]:
Prds = Prds.merge(
    Cat_Prds[['Category_id', 'Product_Category']], 
    left_on='Product_Category', 
    right_on='Product_Category', 
    how='left'
)

In [331]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003,NaN
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003,NaN
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003,NaN
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003,NaN
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003,NaN

In [332]:
Prds[Prds['Category_id'].isna()]['Product_Category'].value_counts()

Product_Category
Produits laitiers       1388
Alimentation animale     289
Name: count, dtype: int64

In [333]:
Cat_Prds['Product_Category'].value_counts()

Product_Category
Alimentaion animale      1
Produits Bébé            1
Charcuterie              1
Boulangerie              1
Vêtements                1
Confiseries              1
Boissons                 1
Electroménager           1
Courses                  1
Loisirs                  1
Hygiène                  1
Produits surgelés        1
Entretien & Nettoyage    1
Produits laities         1
Épices                   1
Électroniques            1
Name: count, dtype: int64

In [334]:

Cat_Prds['Product_Category'] = Cat_Prds['Product_Category'].replace({
    'Alimentaion animale': 'Alimentation animale',
    'Produits laities': 'Produits laitiers'
})

In [335]:
Prds = Prds.drop(columns=['Category_id'])

In [336]:
Prds = Prds.merge(
    Cat_Prds[['Category_id','Product_Category']],
    left_on = 'Product_Category',
    right_on = 'Product_Category',
    how = 'left'
)

In [337]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003,PROD-001
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003,PROD-001
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003,PROD-001
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003,PROD-001
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003,PROD-001

In [338]:
Prds['Category_id'].isna().sum()

np.int64(0)

In [339]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003,PROD-001
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003,PROD-001
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003,PROD-001
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003,PROD-001
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003,PROD-001

In [340]:
Prds['Produit_SKU'].is_unique

False

In [341]:
Prds['Produit_SKU'].duplicated().sum()

np.int64(468)

In [342]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003,PROD-001
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003,PROD-001
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003,PROD-001
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003,PROD-001
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003,PROD-001

In [343]:
dupes = Prds[Prds.duplicated(subset=['Produit_SKU'], keep=False)].sort_values('Produit_SKU')
dupes.head(20)

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
4265,10110-112,Boîte de Cartouches d'encre Bleu Bic 24 unités,15.92,19.9,Loisirs,SUPP-275,PROD-010
4267,10110-112,Boîte de Cartouches d'encre Bleu Bic 24 unités,15.92,19.9,Loisirs,SUPP-275,PROD-010
4264,10110-112,Boîte de Cartouches d'encre Bleu Bic 24 unités,15.92,19.9,Loisirs,SUPP-161,PROD-010
4266,10110-112,Boîte de Cartouches d'encre Bleu Bic 24 unités,15.92,19.9,Loisirs,SUPP-161,PROD-010
4270,10110-115,Boîte de Pâtes à Modeler Kids Plasticine BIC 1...,19.92,24.9,Loisirs,SUPP-161,PROD-010
4271,10110-115,Boîte de Pâtes à Modeler Kids Plasticine BIC 1...,19.92,24.9,Loisirs,SUPP-275,PROD-010
4272,10110-115,Boîte de Pâtes à Modeler Kids Plasticine BIC 1...,19.92,24.9,Loisirs,SUPP-161,PROD-010
4273,10110-115,Boîte de Pâtes à Modeler Kids Plasticine BIC 1...,19.92,24.9,Loisirs,SUPP-275,PROD-010
4129,10110-19,Ardoise Effaçable à Sec 19x26cm + 1 Feutre + 1...,21.52,26.9,Loisirs,SUPP-161,PROD-010
4130,10110-19,Ardoise Effaçable à Sec 19x26cm + 1 Feutre + 1...,21.52,26.9,Loisirs,SUPP-275,PROD-010
4131,10110-19,Ardoise Effaçable à Sec 19x26cm + 1 Feutre + 1...,21.52,26.9,Loisirs,SUPP-161,PROD-010
4132,10110-19,Ardoise Effaçable à Sec 19x26cm + 1 Feutre + 1...,21.52,26.9,Loisirs,SUPP-275,PROD-010
4353,10110-194,Colle Stick BIC 21g 2 unités,22.32,27.9,Loisirs,SUPP-275,PROD-010
4354,10110-194,Colle Stick BIC 21g 2 unités,22.32,27.9,Loisirs,SUPP-161,PROD-010
4352,10110-194,Colle Stick BIC 21g 2 unités,22.32,27.9,Loisirs,SUPP-161,PROD-010
4355,10110-194,Colle Stick BIC 21g 2 unités,22.32,27.9,Loisirs,SUPP-275,PROD-010
4360,10110-199,Colle Stick Shrink Wrap Bic 5x8g,24.72,30.9,Loisirs,SUPP-161,PROD-010
4362,10110-199,Colle Stick Shrink Wrap Bic 5x8g,24.72,30.9,Loisirs,SUPP-161,PROD-010
4363,10110-199,Colle Stick Shrink Wrap Bic 5x8g,24.72,30.9,Loisirs,SUPP-275,PROD-010
4361,10110-199,Colle Stick Shrink Wrap Bic 5x8g,24.72,30.9,Loisirs,SUPP-275,PROD-010

In [344]:
# Fournisseur le plus fréquent par SKU d'après les transactions réelles
fournisseur_reel = (
    Trans.merge(Prds[['Produit_SKU','Fournisseur_id']], on='Produit_SKU')
    .groupby('Produit_SKU')['Fournisseur_id']
    .agg(lambda x: x.value_counts().idxmax())
)

Prds = Prds.drop_duplicates(subset=['Produit_SKU'], keep='first').set_index('Produit_SKU')
Prds.update(fournisseur_reel.rename('Fournisseur_id').to_frame())
Prds = Prds.reset_index()

print(Prds['Produit_SKU'].is_unique)  # doit être True

True

In [345]:
Prds['Produit_SKU'].duplicated().sum()

np.int64(0)

In [379]:
Prds.head()

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.40,113.0,Alimentation animale,SUPP-003,PROD-001
1,10020-2,"Croquettes au Bœuf, Foie et aux Légumes pour C...",87.20,109.0,Alimentation animale,SUPP-003,PROD-001
2,10020-3,Croquettes pour Chiens Bœuf et Légume AYDI 10kg,199.20,249.0,Alimentation animale,SUPP-003,PROD-001
3,10020-4,Patée pour Chats Émincés en Sauce AYDI 12x100g,32.48,40.6,Alimentation animale,SUPP-003,PROD-001
4,10020-5,Pâtée pour Chat AYDI Companino 4x85g,35.60,44.5,Alimentation animale,SUPP-003,PROD-001

## 2.5 Transactions

In [346]:
T1.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,31000,02/11/2025 02:17,10160-2184,Pâte à Tartiner Biscoff Crunchy Lotus 380g,16,"76,50 DH","1224,00 DH",SM-065,Dari,Épices
1,31001,28/05/2025 04:22,10160-2794,Sirop d'Érable Maple Joe 250g,7,"124,95 DH","874,65 DH",SM-174,Pescada,Épices
2,31002,13/01/2025 16:32,10160-657,Café en Dosettes Equilibré Pur Arabica 36 unités,19,"53,80 DH","1022,20 DH",SM-136,VCR SODALMU,Épices
3,31003,17/01/2025 00:38,10160-26,Sauce Tomate au Basilic Florelli 250g,9,"36,90 DH","332,10 DH",SM-158,Florelli,Épices
4,31004,14/07/2025 20:55,10160-924,Confiture de Fraise Sans Sucre Saint Dalfour 2...,18,"59,30 DH","1067,40 DH",SM-268,Macao,Épices

In [347]:
T2.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,61011,17/04/2025 08:26,10030-218,Couches-Culottes Junior Taille 5 Premium Pampe...,20,"151,95 DH","3039,00 DH",SM-018,Pampers,Produits Bébé
1,61012,12/12/2025 18:44,10030-14,Shampooing Bébé Shinydrops Johnson' Baby 500ml,6,"74,95 DH","449,70 DH",SM-253,Johnson & Johnson,Produits Bébé
2,61013,21/05/2025 14:01,10030-92,Compote Pommes Pêches Blédina 130g,35,"19,00 DH","665,00 DH",SM-220,Blédina,Produits Bébé
3,61014,22/02/2025 19:52,10030-175,Compotes en Gourde Pomme Sans Sucres Carrefour...,46,"27,35 DH","1258,10 DH",SM-143,Wee Baby,Produits Bébé
4,61015,19/02/2025 01:37,10030-34,Sucette pour Bébé Orthdontique Wee Baby,6,"39,90 DH","239,40 DH",SM-176,Wee Baby,Produits Bébé

In [348]:
T3.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,890084,10/06/2025 19:05,10130-19,Cornets Glace Crème Brûlée Extra 6 unités 417g.,12,"36,65 DH","439,80 DH",SM-057,Yasmina Ice,Produits surgelés
1,890085,10/06/2025 19:14,10130-358,Haricots Verts Extra Fins Findus 400g,9,"40,50 DH","364,50 DH",SM-235,Goldy,Produits surgelés
2,890086,10/06/2025 19:22,10130-121,Bâtonnet Feast Walls 80ml,13,"11,00 DH","143,00 DH",SM-171,Pingouin Glace,Produits surgelés
3,890087,10/06/2025 19:31,10130-492,Polo Cola La Menorquina 150ml,1,"16,95 DH","16,95 DH",SM-304,Nestlé,Produits surgelés
4,890088,10/06/2025 19:40,10130-234,Crème Glacée Chocolat Cornet Delicio Corne 70ml,7,"2,70 DH","18,90 DH",SM-126,Pingouin Glace,Produits surgelés

In [349]:
T4.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,921118,26/08/2025 11:24,10110-294,Flûte en Plastique Maped Trous Baroque,71,"55,90 DH","3968,90 DH",SM-179,Maped,Loisirs
1,921119,09/02/2025 18:28,10110-482,"Poupée avec 2 Robes Anlily 33x22x6,5cm",120,"69,90 DH","8388,00 DH",SM-193,Deli Group,Loisirs
2,921120,24/11/2025 01:20,10110-409,Mini Trousse à Crayons 30g,83,"19,90 DH","1651,70 DH",SM-216,Deli Group,Loisirs
3,921121,31/03/2025 04:29,10110-643,Surligneurs en Ligne Jaune Orange Rose Bleu 4 ...,92,"7,90 DH","726,80 DH",SM-186,Deli Group,Loisirs
4,921122,10/09/2025 00:51,10110-518,Puzzle Pinocchio Double Facef Super Maxi 108 P...,132,"99,90 DH","13186,80 DH",SM-186,Deli Group,Loisirs

In [350]:
Trans = pd.concat([T1,T2,T3,T4] , ignore_index = True)

In [351]:
Trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111475 entries, 0 to 111474
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       111475 non-null  int64
 1   Date                 111475 non-null  object
 2   product_sku          111475 non-null  object
 3   Produit_Désignation  111475 non-null  object
 4   Quantité             111475 non-null  int64
 5   Prix de Vente        111475 non-null  object
 6   Ventes               111475 non-null  object
 7   store_id             111475 non-null  object
 8   Fournisseur          111475 non-null  object
 9   Catégorie            111475 non-null  object
dtypes: int64(2), object(8)
memory usage: 8.5+ MB

In [352]:
Trans.duplicated().sum()

np.int64(0)

In [353]:
Trans['Date'] = pd.to_datetime(Trans['Date'], format='mixed', errors='coerce')

In [354]:
Trans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111475 entries, 0 to 111474
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   transaction_id       111475 non-null  int64
 1   Date                 111475 non-null  datetime64[ns]
 2   product_sku          111475 non-null  object
 3   Produit_Désignation  111475 non-null  object
 4   Quantité             111475 non-null  int64
 5   Prix de Vente        111475 non-null  object
 6   Ventes               111475 non-null  object
 7   store_id             111475 non-null  object
 8   Fournisseur          111475 non-null  object
 9   Catégorie            111475 non-null  object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 8.5+ MB

In [355]:
Trans['Prix de Vente'] = (
    Trans['Prix de Vente']
    .astype(str)
    .str.replace('dh', '', case=False, regex=True)
    .str.replace(',', '.')
    .str.strip()
    .astype(float)
)

In [356]:
Trans['Ventes'] = (
    Trans['Ventes']
    .astype(str)
    .str.replace('dh', '', case=False, regex=True)
    .str.replace(',', '.')
    .str.strip()
    .astype(float)
)

In [357]:
Trans.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,31000,2025-02-11 02:17:00,10160-2184,Pâte à Tartiner Biscoff Crunchy Lotus 380g,16,76.50,1224.00,SM-065,Dari,Épices
1,31001,2025-05-28 04:22:00,10160-2794,Sirop d'Érable Maple Joe 250g,7,124.95,874.65,SM-174,Pescada,Épices
2,31002,2025-01-13 16:32:00,10160-657,Café en Dosettes Equilibré Pur Arabica 36 unités,19,53.80,1022.20,SM-136,VCR SODALMU,Épices
3,31003,2025-01-17 00:38:00,10160-26,Sauce Tomate au Basilic Florelli 250g,9,36.90,332.10,SM-158,Florelli,Épices
4,31004,2025-07-14 20:55:00,10160-924,Confiture de Fraise Sans Sucre Saint Dalfour 2...,18,59.30,1067.40,SM-268,Macao,Épices

In [358]:
Trans.head()

,transaction_id,Date,product_sku,Produit_Désignation,Quantité,Prix de Vente,Ventes,store_id,Fournisseur,Catégorie
0,31000,2025-02-11 02:17:00,10160-2184,Pâte à Tartiner Biscoff Crunchy Lotus 380g,16,76.50,1224.00,SM-065,Dari,Épices
1,31001,2025-05-28 04:22:00,10160-2794,Sirop d'Érable Maple Joe 250g,7,124.95,874.65,SM-174,Pescada,Épices
2,31002,2025-01-13 16:32:00,10160-657,Café en Dosettes Equilibré Pur Arabica 36 unités,19,53.80,1022.20,SM-136,VCR SODALMU,Épices
3,31003,2025-01-17 00:38:00,10160-26,Sauce Tomate au Basilic Florelli 250g,9,36.90,332.10,SM-158,Florelli,Épices
4,31004,2025-07-14 20:55:00,10160-924,Confiture de Fraise Sans Sucre Saint Dalfour 2...,18,59.30,1067.40,SM-268,Macao,Épices

In [359]:
Trans = Trans.rename(columns = {
    'product_sku' : 'Produit_SKU',
    'Produit_Désignation': 'Produit_Designation',
    'Quantité': 'Quantite',
    'Prix de Vente' : 'Prix_Vente',
    'store_id' : 'magasin_id'
})

In [360]:
Trans.head()

,transaction_id,Date,Produit_SKU,Produit_Designation,Quantite,Prix_Vente,Ventes,magasin_id,Fournisseur,Catégorie
0,31000,2025-02-11 02:17:00,10160-2184,Pâte à Tartiner Biscoff Crunchy Lotus 380g,16,76.50,1224.00,SM-065,Dari,Épices
1,31001,2025-05-28 04:22:00,10160-2794,Sirop d'Érable Maple Joe 250g,7,124.95,874.65,SM-174,Pescada,Épices
2,31002,2025-01-13 16:32:00,10160-657,Café en Dosettes Equilibré Pur Arabica 36 unités,19,53.80,1022.20,SM-136,VCR SODALMU,Épices
3,31003,2025-01-17 00:38:00,10160-26,Sauce Tomate au Basilic Florelli 250g,9,36.90,332.10,SM-158,Florelli,Épices
4,31004,2025-07-14 20:55:00,10160-924,Confiture de Fraise Sans Sucre Saint Dalfour 2...,18,59.30,1067.40,SM-268,Macao,Épices

In [361]:
len(Trans[~Trans['Produit_SKU'].isin(Prds['Produit_SKU'])])

45

In [362]:
Produits_manquantes = Trans[~Trans['Produit_SKU'].isin(Prds['Produit_SKU'])][['Produit_SKU', 'Produit_Designation']].drop_duplicates()

In [363]:
Produits_manquantes

       Produit_SKU                                Produit_Designation
946      10160-229  Conserve de Thon à l'Huile de Tournesol Isabel...
997     10160-2143  Pack de Trois Conserves de Thon à l'Huile de T...
1182    10160-1047      Conserve de Thon à la Sauce Tomate Isabel 80g
3797    10160-2149  Pack de Trois Conserves de Thon à la Sauce Tom...
10380    10070-765     Chewing-Gum Citron et Menthe Clorets 10 unités
11303    10150-733                Fromage Fondu Land' Or 48 portions.
11674    10150-732                  Fromage Fondu Land Or 64 portions
101735  10160-2147  Pack de Trois Conserves de Thon à la Sauce lah...

In [364]:
len(Produits_manquantes)

8

In [365]:
Trans['Produit_SKU'] = Trans['Produit_SKU'].astype(str).str.strip()
Prds['Produit_SKU'] = Prds['Produit_SKU'].astype(str).str.strip()

In [366]:
len(Trans[~Trans['Produit_SKU'].isin(Prds['Produit_SKU'])][['Produit_SKU']].drop_duplicates())

8

In [372]:
nouveaux_produits = Trans[~Trans['Produit_SKU'].isin(Prds['Produit_SKU'])][
    ['Produit_SKU', 'Produit_Designation', 'Fournisseur', 'Catégorie']
].drop_duplicates(subset=['Produit_SKU']).rename(columns={
    'Fournisseur': 'Fournisseur_Nom',
    'Catégorie': 'Product_Category'
})

nouveaux_produits['Fournisseur_Nom'] = (
    nouveaux_produits['Fournisseur_Nom'].astype(str).str.strip().str.upper()
)

nouveaux_produits = nouveaux_produits.merge(
    Frs[['Fournisseur_id', 'Fournisseur_Nom']], on='Fournisseur_Nom', how='left'
)
nouveaux_produits = nouveaux_produits.merge(
    Cat_Prds[['Category_id', 'Product_Category']], on='Product_Category', how='left'
)

nouveaux_produits = nouveaux_produits[
    ['Produit_SKU', 'Produit_Designation', 'Fournisseur_id', 'Category_id','Product_Category']
]
nouveaux_produits['Prix_Achat'] = np.nan
nouveaux_produits['Prix_vente'] = np.nan
nouveaux_produits = nouveaux_produits[Prds.columns]

Prds = pd.concat([Prds, nouveaux_produits], ignore_index=True)

len(Trans[~Trans['Produit_SKU'].isin(Prds['Produit_SKU'])])

0

In [373]:
Trans.head(1)

,transaction_id,Date,Produit_SKU,Produit_Designation,Quantite,Prix_Vente,Ventes,magasin_id,Fournisseur,Catégorie
0,31000,2025-02-11 02:17:00,10160-2184,Pâte à Tartiner Biscoff Crunchy Lotus 380g,16,76.5,1224.0,SM-065,Dari,Épices

In [374]:
Trans= Trans.drop(columns=['Fournisseur', 'Catégorie', 'Produit_Designation'], errors = 'ignore')

In [375]:
Trans.head()

,transaction_id,Date,Produit_SKU,Quantite,Prix_Vente,Ventes,magasin_id
0,31000,2025-02-11 02:17:00,10160-2184,16,76.50,1224.00,SM-065
1,31001,2025-05-28 04:22:00,10160-2794,7,124.95,874.65,SM-174
2,31002,2025-01-13 16:32:00,10160-657,19,53.80,1022.20,SM-136
3,31003,2025-01-17 00:38:00,10160-26,9,36.90,332.10,SM-158
4,31004,2025-07-14 20:55:00,10160-924,18,59.30,1067.40,SM-268

In [376]:
len(Trans[~Trans['magasin_id'].isin(Mag['magasin_id'])][['magasin_id']].drop_duplicates())

37

In [377]:
magasins_manquants = Trans[~Trans['magasin_id'].isin(Mag['magasin_id'])]['magasin_id'].unique()

In [378]:
magasins_manquants

array(['SM-310', 'SM-338', 'SM-314', 'SM-346', 'SM-316', 'SM-348',
       'SM-323', 'SM-311', 'SM-345', 'SM-331', 'SM-358', 'SM-336',
       'SM-347', 'SM-312', 'SM-339', 'SM-321', 'SM-362', 'SM-356',
       'SM-342', 'SM-322', 'SM-326', 'SM-335', 'SM-313', 'SM-317',
       'SM-324', 'SM-315', 'SM-318', 'SM-320', 'SM-334', 'SM-327',
       'SM-341', 'SM-332', 'SM-352', 'SM-359', 'SM-344', 'SM-325',
       'SM-333'], dtype=object)

In [380]:
# 1. Nettoyer la colonne fantôme déjà créée
Mag = Mag.drop(columns=['Région'], errors='ignore')

# 2. Recréer nouveaux_magasins avec le bon nom de colonne dès le départ
nouveaux_magasins = pd.DataFrame({
    'magasin_id': magasins_manquants,
    'Zone': 'Inconnu',
    'Ville': 'Inconnu',
    'Region': 'Inconnu',      # <-- corrigé : 'Region' sans accent, comme dans Mag
    'Adresse': 'Inconnu'
})

# 3. Concaténer proprement — les colonnes matchent, plus de fantôme
Mag = pd.concat([Mag, nouveaux_magasins], ignore_index=True)

# 4. Contrôle
print(Mag.columns.tolist())                     # doit rester à 5 colonnes
print(Mag.isnull().sum())                        # aucune colonne 'Région' résiduelle
print(len(Trans[~Trans['magasin_id'].isin(Mag['magasin_id'])]))  # doit être 0
Mag.tail(3)                                       # vérifier que les 37 nouveaux ont bien Region='Inconnu'

['magasin_id', 'Zone', 'Ville', 'Region', 'Adresse']
magasin_id    0
Zone          0
Ville         0
Region        0
Adresse       0
dtype: int64
0

    magasin_id     Zone    Ville   Region  Adresse
343     SM-344  Inconnu  Inconnu  Inconnu  Inconnu
344     SM-325  Inconnu  Inconnu  Inconnu  Inconnu
345     SM-333  Inconnu  Inconnu  Inconnu  Inconnu

In [381]:
len(Trans[~Trans['magasin_id'].isin(Mag['magasin_id'])])

0

In [382]:
Mag.head(1)

,magasin_id,Zone,Ville,Region,Adresse
0,SM-001,AIN CHOCK/QUARTIER CALIFORNIE,Casablanca,Casablanca-Settat,Californie 1

In [383]:
Trans['transaction_id'].is_unique

False

In [221]:
Trans['transaction_id'].duplicated().sum()

np.int64(727)

In [384]:
dupe_trans = Trans[Trans.duplicated(subset=['transaction_id'], keep=False)].sort_values('transaction_id')
print(len(dupe_trans))
dupe_trans.head(20)

1454

,transaction_id,Date,Produit_SKU,Quantite,Prix_Vente,Ventes,magasin_id
57585,88969,2025-05-01 09:15:00,10140-512,7,13.75,96.25,SM-125
57586,88969,2025-03-20 18:25:00,10120-1700,6,98.00,588.00,SM-339
57587,88970,2025-05-01 09:24:00,10140-247,3,21.65,64.95,SM-089
57588,88970,2025-03-20 18:34:00,10120-462,24,139.00,3336.00,SM-064
57590,88971,2025-03-20 18:43:00,10120-1391,1,94.95,94.95,SM-281
57589,88971,2025-05-01 09:33:00,10140-876,9,36.35,327.15,SM-278
57591,88972,2025-05-01 09:42:00,10140-43,5,28.95,144.75,SM-042
57592,88972,2025-03-20 18:51:00,10120-2221,13,61.95,805.35,SM-103
57593,88973,2025-05-01 09:51:00,10140-654,2,22.80,45.60,SM-196
57594,88973,2025-03-20 19:00:00,10120-1776,20,72.00,1440.00,SM-249
57595,88974,2025-05-01 10:00:00,10140-321,8,7.50,60.00,SM-303
57596,88974,2025-03-20 19:09:00,10120-205,8,42.95,343.60,SM-167
57597,88975,2025-05-01 10:09:00,10140-789,6,27.50,165.00,SM-077
57598,88975,2025-03-20 19:18:00,10120-1132,17,31.95,543.15,SM-308
57600,88976,2025-03-20 19:27:00,10120-1955,10,26.95,269.50,SM-044
57599,88976,2025-05-01 10:18:00,10140-98,10,5.00,50.00,SM-154
57602,88977,2025-03-20 19:35:00,10120-1508,25,16.95,423.75,SM-190
57601,88977,2025-05-01 10:27:00,10140-567,1,111.95,111.95,SM-231
57603,88978,2025-05-01 10:35:00,10140-412,4,39.50,158.00,SM-005
57604,88978,2025-03-20 19:44:00,10120-2240,3,155.95,467.85,SM-212

In [385]:
# Compte combien de transaction_id dupliqués sont EXACTEMENT la même ligne (toutes colonnes)
vraies_dupes = Trans[Trans.duplicated(keep=False)]
print("Lignes strictement identiques dupliquées:", len(vraies_dupes))

# Compte combien de transaction_id dupliqués correspondent à des transactions différentes (collision d'ID)
collisions = Trans[Trans.duplicated(subset=['transaction_id'], keep=False) & ~Trans.duplicated(keep=False)]
print("Lignes avec ID en collision mais contenu différent:", len(collisions))

Lignes strictement identiques dupliquées: 0
Lignes avec ID en collision mais contenu différent: 1454

In [386]:
# 1. Confirmer d'où viennent les collisions (optionnel mais utile à documenter)
collisions = Trans[Trans.duplicated(subset=['transaction_id'], keep=False)]
print(collisions.sort_values('transaction_id').head(10))

# 2. Garder l'ID d'origine pour traçabilité, puis générer un ID définitif garanti unique
Trans = Trans.reset_index(drop=True)
Trans['transaction_id_original'] = Trans['transaction_id']
Trans['transaction_id'] = Trans.index + 1

# 3. Contrôle final
print(Trans['transaction_id'].is_unique)          # doit être True
print(Trans['transaction_id'].duplicated().sum())  # doit être 0
Trans.head()

       transaction_id                Date Produit_SKU  Quantite  Prix_Vente  \
57585           88969 2025-05-01 09:15:00   10140-512         7       13.75
57586           88969 2025-03-20 18:25:00  10120-1700         6       98.00
57587           88970 2025-05-01 09:24:00   10140-247         3       21.65
57588           88970 2025-03-20 18:34:00   10120-462        24      139.00
57590           88971 2025-03-20 18:43:00  10120-1391         1       94.95
57589           88971 2025-05-01 09:33:00   10140-876         9       36.35
57591           88972 2025-05-01 09:42:00    10140-43         5       28.95
57592           88972 2025-03-20 18:51:00  10120-2221        13       61.95
57593           88973 2025-05-01 09:51:00   10140-654         2       22.80
57594           88973 2025-03-20 19:00:00  10120-1776        20       72.00

        Ventes magasin_id
57585    96.25     SM-125
57586   588.00     SM-339
57587    64.95     SM-089
57588  3336.00     SM-064
57590    94.95     SM-281
57589   327.15     SM-278
57591   144.75     SM-042
57592   805.35     SM-103
57593    45.60     SM-196
57594  1440.00     SM-249
True
0

,transaction_id,Date,Produit_SKU,Quantite,Prix_Vente,Ventes,magasin_id,transaction_id_original
0,1,2025-02-11 02:17:00,10160-2184,16,76.50,1224.00,SM-065,31000
1,2,2025-05-28 04:22:00,10160-2794,7,124.95,874.65,SM-174,31001
2,3,2025-01-13 16:32:00,10160-657,19,53.80,1022.20,SM-136,31002
3,4,2025-01-17 00:38:00,10160-26,9,36.90,332.10,SM-158,31003
4,5,2025-07-14 20:55:00,10160-924,18,59.30,1067.40,SM-268,31004

## 3. Export vers SQL Server

In [388]:
print(Trans['transaction_id'].is_unique)

True

In [389]:
print(Prds['Produit_SKU'].is_unique)

True

In [391]:
print(Cat_Prds['Category_id'].is_unique)

True

In [392]:
print(Frs['Fournisseur_id'].is_unique)

True

In [393]:
print(Mag['magasin_id'].is_unique)

True

In [394]:
Trans.head(1)

,transaction_id,Date,Produit_SKU,Quantite,Prix_Vente,Ventes,magasin_id,transaction_id_original
0,1,2025-02-11 02:17:00,10160-2184,16,76.5,1224.0,SM-065,31000

In [395]:
Prds.head(1)

,Produit_SKU,Produit_Designation,Prix_Achat,Prix_vente,Product_Category,Fournisseur_id,Category_id
0,10020-1,Croquettes au Bœuf et Légumes Chiens Adultes A...,90.4,113.0,Alimentation animale,SUPP-003,PROD-001

In [396]:
Mag.head(1)

,magasin_id,Zone,Ville,Region,Adresse
0,SM-001,AIN CHOCK/QUARTIER CALIFORNIE,Casablanca,Casablanca-Settat,Californie 1

In [397]:
Frs.head(1)

,Fournisseur_id,Fournisseur_Nom,Founisseur_image
0,SUPP-001,PRODUITS IMPORTÉS,https://www.gtreview.com/wp-content/uploads/20...

In [398]:
Cat_Prds.head(1)

,Category_id,Product_Category,Category_Image
0,PROD-001,Alimentation animale,https://images.pexels.com/photos/8434637/pexel...

## 3.1 Connexion à la base de données

In [400]:
from sqlalchemy import create_engine

engine = create_engine(
    r"mssql+pyodbc://DESKTOP-6FVV2LJ\MSSQLSERVER01/Gestion_Ventes?"
    "driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

with engine.connect() as conn:
    print("Connexion réussie")

Connexion réussie

In [401]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server']

## 3.2 Export des tables

In [402]:
from sqlalchemy import types

# 1. Catégorie des produits (aucune dépendance)
Cat_Prds.to_sql('Categorie_Produits', engine, if_exists='replace', index=False, dtype={
    'Category_id': types.VARCHAR(20),
    'Product_Category': types.NVARCHAR(100),
    'Category_Image': types.NVARCHAR(500)
})
print("Categorie_Produits exportée")

Categorie_Produits exportée

In [403]:
# 2 . Fournisseurs : 
Frs.to_sql('Fournisseur' , engine , if_exists='replace' , index = False, dtype={
    'Fournisseur_id': types.VARCHAR(20),
    'Fournisseur_Nom': types.NVARCHAR(255),
    'Founisseur_image': types.NVARCHAR(500)
})
print('fournisseur exportée')

fournisseur exportée

In [404]:
# 3. Magasins (aucune dépendance)
Mag.to_sql('Magasins', engine, if_exists='replace', index=False, dtype={
    'magasin_id': types.VARCHAR(20),
    'Zone': types.NVARCHAR(255),
    'Ville': types.NVARCHAR(100),
    'Region': types.NVARCHAR(100),
    'Adresse': types.NVARCHAR(255)
})
print("Magasins exportée")

Magasins exportée

In [405]:
# 4. Produits (dépend de Fournisseurs + Categorie_Produits)
Prds.to_sql('Produits', engine, if_exists='replace', index=False, dtype={
    'Produit_SKU': types.VARCHAR(20),
    'Produit_designation': types.NVARCHAR(255),
    'Prix_Achat': types.DECIMAL(10,2),
    'Prix_vente': types.DECIMAL(10,2),
    'Fournisseur_id': types.VARCHAR(20),
    'Category_id': types.VARCHAR(20)
})
print("Produits exportée")

Produits exportée

In [406]:
# 5. Transactions (dépend de Produits + Magasins)
Trans.to_sql('Transactions', engine, if_exists='replace', index=False, dtype={
    'transaction_id': types.INTEGER(),
    'transaction_id_original': types.INTEGER(),
    'Date': types.DATETIME(),
    'Produit_SKU': types.VARCHAR(20),
    'Quantite': types.INTEGER(),
    'Prix_Vente': types.DECIMAL(10,2),
    'Ventes': types.DECIMAL(10,2),
    'magasin_id': types.VARCHAR(20)
})
print("Transactions exportée")

Transactions exportée